create user 'tianlangdev'@'%' IDENTIFIED by 'cyhd2017';
GRANT ALL PRIVILEGES ON *.* TO 'tianlangdev'@'%'  WITH GRANT OPTION;

mysql -u root -p -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';"
